# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
  - url: "http://127.0.0.1:8086/api/v1/prom/write?db={{ influxdb_databasename }}&u={{ influxdb_user }}&p={{ influxdb_user_password }}"

# Remote read configuration (for InfluxDB only at the moment).
remote_read:
  - url: "http://127.0.0.1:8086/api/v1/prom/read?db={{ influxdb_databasename }}&u={{ influxdb_user }}&p={{ influxdb_user_password }}"
    read_recent: true

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
{% for f in alert_rule_files.files %}
  - {{ f.path }}
{% endfor %}

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['127.0.0.1:9090']

